---
- name: Проверка версии
  shell: node_exporter --version 2>&1 | awk '/node_exporter, version [[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+/ { print $3 }'
  register: node_exporter_version_installed
  ignore_errors: true
  changed_when: false

- name: Загрузка Node Exporter
  unarchive:
    src: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp
    remote_src: true
  when: node_exporter_version_installed.stdout != node_exporter_version

- name: Копируем бинари
  become: true
  copy:
    src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64/node_exporter"
    dest: /usr/local/bin/node_exporter
    remote_src: true
    mode: 0755
    owner: root
    group: root
  when: node_exporter_version_installed.stdout != node_exporter_version
  notify: restart node_exporter

- name: Зачищаем
  file:
    dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64"
    state: absent

- name: Запускаем как сервис
  become: true
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    mode: 0644
    owner: root
    group: root
  notify: restart node_exporter
