---
- name: Install nginx
  yum:
    name: nginx
    state: present


#- name: selinux port
#  command: semanage port -a -t http_port_t -p tcp 443

- name: Disable default route (vagrant)
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth0
    line: "DEFROUTE=no"
  notify: restart network

- name: Add default route
  lineinfile:
    path: /etc/sysconfig/network-scripts/ifcfg-eth2
    line: "GATEWAY=192.168.255.1"
  notify: restart network

- name: Restart network (vagrant bug)
  service:
    name: network
    state: restarted


- name: копируем upstream.conf
  copy:
    src: upstream.conf
    dest: /etc/nginx/upstream.conf

- name: Файл сертификата
  copy:
    src: mysite.localhost.crt
    dest: /home/vagrant/mysite.localhost.crt

- name: Ключ сертификата
  copy:
    src: device.key
    dest: /home/vagrant/device.key

- name: create sites-available and sites-enabled directory
  file: 
    name: /etc/nginx/sites-available
    state: directory

- file:
    src: /etc/nginx/sites-available
    dest: /etc/nginx/sites-enabled
    state: link

#- name: copy nginx conf files
#  copy:
#    src: project.local.conf
#    dest: /etc/nginx/sites-available/project.local.conf

- copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf


- name: selinux task
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes

- name: allow web to listen on tcp port 443
  seport:
    ports: 443
    proto: tcp
    setype: http_port_t
    state: present

- name: allow web to listen on tcp port 80
  seport:
    ports: 80
    proto: tcp
    setype: http_port_t
    state: present




- name: Apply new SELinux SSL context
  command: chcon unconfined_u:object_r:httpd_config_t:s0 /home/vagrant/mysite.localhost.crt

- name: Apply new SELinux SSL context
  command: chcon unconfined_u:object_r:httpd_config_t:s0 /home/vagrant/device.key


- name: start nginx
  service:
    name: nginx
    state: started
    enabled: yes



- name: start firewalld
  service:
    name: firewalld
    state: started
    enabled: yes

- name: Добавим порт 443 в разрешенные для firewalld
  firewalld:
    zone: internal
    port: 443/tcp
    permanent: yes
    state: enabled
    immediate: yes
    
- name: Добавим порт 80 в разрешенные для firewalld
  firewalld:
    zone: internal
    port: 80/tcp
    permanent: yes
    state: enabled
    immediate: yes


- name: add DMZ zone (1)
  command: firewall-cmd --zone=dmz --permanent --add-interface=eth2

- name: add internal zone (1)
  command: firewall-cmd --zone=internal --permanent --add-interface=eth1

- name: enable firewalld http at dmz
  firewalld:
    zone: dmz
    service: http
    permanent:  yes
    state: enabled
    immediate:  yes
    
    
    
    
    
