---
- name: Configure datasources
  become: true
  template:
    src: datasource.yaml.j2
    dest: "/etc/grafana/provisioning/datasources/{{ item.name }}.yaml"
    mode: 0640
    owner: root
    group: grafana
  loop: "{{ grafana_datasources }}"
  notify: restart grafana
